//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qUTe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("qUTe.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27100
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSA1_S1 {
            get {
                return ResourceManager.GetString("BSA1_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27200
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSA1_S2 {
            get {
                return ResourceManager.GetString("BSA1_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27300
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSA1_S3 {
            get {
                return ResourceManager.GetString("BSA1_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27100
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSA2_S1 {
            get {
                return ResourceManager.GetString("BSA2_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27200
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSA2_S2 {
            get {
                return ResourceManager.GetString("BSA2_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27300
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BSA2_S3 {
            get {
                return ResourceManager.GetString("BSA2_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=7777
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAudi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTO {
            get {
                return ResourceManager.GetString("BTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VehicleStuff.VehicleStuff]
        ///VPsLength=13
        ///VehicleWeaponsLength=19
        ///ProjectilesLength=12
        ///VPs[0]=(VehicleName=&quot;Anti-Air HellBender&quot;,VehicleClass=&quot;TIMPRV.TIMPRV&quot;,SpeedScale=1.000000,friction=1.000000,Mass=1.000000,WheelScale=1.000000,JumpHeight=1.000000,HoverHeight=1.000000,Health=800,bCanJump=False,DWeapons[0]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),DWeapons[1]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),PWeapons[0]=(WeaponClass=&quot;Onslaught.ONSTankSecondaryTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTO_VehicleStuff {
            get {
                return ResourceManager.GetString("BTO_VehicleStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ROOtator.MutRoos]
        ///bAussieRooLette=True
        ///bHideTNT=False
        ///RooLetteTimer=0.000000
        ///bRooHunt=True
        ///bRooHuntMatch=False
        ///RHMaxLives=0
        ///bRooAdrenaline=False
        ///bKeepRoos=True
        ///
        ///.
        /// </summary>
        internal static string BTP_ROOtator {
            get {
                return ResourceManager.GetString("BTP_ROOtator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27100
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTP_S1 {
            get {
                return ResourceManager.GetString("BTP_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27200
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTP_S2 {
            get {
                return ResourceManager.GetString("BTP_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27300
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTP_S3 {
            get {
                return ResourceManager.GetString("BTP_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [ROOtator.MutRoos]
        ///bAussieRooLette=True
        ///bHideTNT=False
        ///RooLetteTimer=0.000000
        ///bRooHunt=True
        ///bRooHuntMatch=False
        ///RHMaxLives=0
        ///bRooAdrenaline=False
        ///bKeepRoos=True
        ///
        ///.
        /// </summary>
        internal static string BTV_ROOtator {
            get {
                return ResourceManager.GetString("BTV_ROOtator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27100
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTV_S1 {
            get {
                return ResourceManager.GetString("BTV_S1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27200
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTV_S2 {
            get {
                return ResourceManager.GetString("BTV_S2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=27300
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTV_S3 {
            get {
                return ResourceManager.GetString("BTV_S3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VehicleStuff.VehicleStuff]
        ///VPsLength=13
        ///VehicleWeaponsLength=19
        ///ProjectilesLength=12
        ///VPs[0]=(VehicleName=&quot;Anti-Air HellBender&quot;,VehicleClass=&quot;TIMPRV.TIMPRV&quot;,SpeedScale=1.000000,friction=1.000000,Mass=1.000000,WheelScale=1.000000,JumpHeight=1.000000,HoverHeight=1.000000,Health=800,bCanJump=False,DWeapons[0]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),DWeapons[1]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),PWeapons[0]=(WeaponClass=&quot;Onslaught.ONSTankSecondaryTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BTV_VehicleStuff {
            get {
                return ResourceManager.GetString("BTV_VehicleStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qUTe_Splash {
            get {
                object obj = ResourceManager.GetObject("qUTe_Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=7777
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAudi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG1E {
            get {
                return ResourceManager.GetString("TG1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VehicleStuff.VehicleStuff]
        ///VPsLength=13
        ///VehicleWeaponsLength=19
        ///ProjectilesLength=13
        ///VPs[0]=(VehicleName=&quot;Anti-Air HellBender&quot;,VehicleClass=&quot;TIMPRV.TIMPRV&quot;,SpeedScale=1.000000,friction=1.000000,Mass=1.000000,WheelScale=1.000000,JumpHeight=1.000000,HoverHeight=1.000000,Health=800,bCanJump=False,DWeapons[0]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),DWeapons[1]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),PWeapons[0]=(WeaponClass=&quot;Onslaught.ONSTankSecondaryTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG1E_VehicleStuff {
            get {
                return ResourceManager.GetString("TG1E_VehicleStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=7777
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAudi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG1H {
            get {
                return ResourceManager.GetString("TG1H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VehicleStuff.VehicleStuff]
        ///VPsLength=13
        ///VehicleWeaponsLength=19
        ///ProjectilesLength=13
        ///VPs[0]=(VehicleName=&quot;Anti-Air HellBender&quot;,VehicleClass=&quot;TIMPRV.TIMPRV&quot;,SpeedScale=1.000000,friction=1.000000,Mass=1.000000,WheelScale=1.000000,JumpHeight=1.000000,HoverHeight=1.000000,Health=800,bCanJump=False,DWeapons[0]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),DWeapons[1]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),PWeapons[0]=(WeaponClass=&quot;Onslaught.ONSTankSecondaryTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG1H_VehicleStuff {
            get {
                return ResourceManager.GetString("TG1H_VehicleStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=7777
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAudi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG1M {
            get {
                return ResourceManager.GetString("TG1M", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VehicleStuff.VehicleStuff]
        ///VPsLength=13
        ///VehicleWeaponsLength=19
        ///ProjectilesLength=13
        ///VPs[0]=(VehicleName=&quot;Anti-Air HellBender&quot;,VehicleClass=&quot;TIMPRV.TIMPRV&quot;,SpeedScale=1.000000,friction=1.000000,Mass=1.000000,WheelScale=1.000000,JumpHeight=1.000000,HoverHeight=1.000000,Health=800,bCanJump=False,DWeapons[0]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),DWeapons[1]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),PWeapons[0]=(WeaponClass=&quot;Onslaught.ONSTankSecondaryTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG1M_VehicleStuff {
            get {
                return ResourceManager.GetString("TG1M_VehicleStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=7777
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAudi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG2 {
            get {
                return ResourceManager.GetString("TG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VehicleStuff.VehicleStuff]
        ///VPsLength=13
        ///VehicleWeaponsLength=19
        ///ProjectilesLength=12
        ///VPs[0]=(VehicleName=&quot;Anti-Air HellBender&quot;,VehicleClass=&quot;TIMPRV.TIMPRV&quot;,SpeedScale=1.000000,friction=1.000000,Mass=1.000000,WheelScale=1.000000,JumpHeight=1.000000,HoverHeight=1.000000,Health=800,bCanJump=False,DWeapons[0]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),DWeapons[1]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),PWeapons[0]=(WeaponClass=&quot;Onslaught.ONSTankSecondaryTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG2_VehicleStuff {
            get {
                return ResourceManager.GetString("TG2_VehicleStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=7777
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAudi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG3 {
            get {
                return ResourceManager.GetString("TG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VehicleStuff.VehicleStuff]
        ///VPsLength=13
        ///VehicleWeaponsLength=19
        ///ProjectilesLength=12
        ///VPs[0]=(VehicleName=&quot;Anti-Air HellBender&quot;,VehicleClass=&quot;TIMPRV.TIMPRV&quot;,SpeedScale=1.000000,friction=1.000000,Mass=1.000000,WheelScale=1.000000,JumpHeight=1.000000,HoverHeight=1.000000,Health=800,bCanJump=False,DWeapons[0]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),DWeapons[1]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),PWeapons[0]=(WeaponClass=&quot;Onslaught.ONSTankSecondaryTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG3_VehicleStuff {
            get {
                return ResourceManager.GetString("TG3_VehicleStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [URL]
        ///Protocol=ut2004
        ///ProtocolDescription=Unreal Protocol
        ///Name=Player
        ///Map=Index.ut2
        ///LocalMap=NvidiaLogo.ut2
        ///NetBrowseMap=Entry.ut2
        ///Host=
        ///Portal=
        ///MapExt=ut2
        ///EXEName=UT2004.exe
        ///SaveExt=usa
        ///Port=7777
        ///Class=Engine.Pawn
        ///Character=Gorge
        ///
        ///[FirstRun]
        ///FirstRun=3369
        ///
        ///[Engine.Engine]
        ///RenderDevice=D3DDrv.D3DRenderDevice
        ///;RenderDevice=D3D9Drv.D3D9RenderDevice
        ///;RenderDevice=Engine.NullRenderDevice
        ///;RenderDevice=OpenGLDrv.OpenGLRenderDevice
        ///;RenderDevice=PixoDrv.PixoRenderDevice
        ///AudioDevice=ALAudi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG4 {
            get {
                return ResourceManager.GetString("TG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [VehicleStuff.VehicleStuff]
        ///VPsLength=13
        ///VehicleWeaponsLength=19
        ///ProjectilesLength=12
        ///VPs[0]=(VehicleName=&quot;Anti-Air HellBender&quot;,VehicleClass=&quot;TIMPRV.TIMPRV&quot;,SpeedScale=1.000000,friction=1.000000,Mass=1.000000,WheelScale=1.000000,JumpHeight=1.000000,HoverHeight=1.000000,Health=800,bCanJump=False,DWeapons[0]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),DWeapons[1]=(WeaponClass=,Mode[0]=,Mode[1]=,Rate[0]=0.000000,Rate[1]=0.000000),PWeapons[0]=(WeaponClass=&quot;Onslaught.ONSTankSecondaryTu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TG4_VehicleStuff {
            get {
                return ResourceManager.GetString("TG4_VehicleStuff", resourceCulture);
            }
        }
    }
}
